<template>
  <section class="privacy-policy-section">
    <div class="container">
      <!-- Logo SIUJI -->
      <div class="logo-header">
        <img :src="logo" alt="SIUJI Logo" class="logo" />
      </div>
      <button @click="goBack" class="back-button">
        ← <span class="back-text">Kembali</span>
      </button>
      <h1>Privacy Policy</h1>
      <p class="update-date">Updated at 2025-08-13</p>
      <div class="policy-content">
        <p>
          SIUJI ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by SIUJI.
        </p>
        <p>
          This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, SIUJI. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service. This Privacy Policy was created with <a href="https://termify.io" target="_blank" rel="noopener">Termify</a>.
        </p>

        <h2>Definitions and key terms</h2>
        <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
        <ul>
          <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
          <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to SIUJI, that is responsible for your information under this Privacy Policy.</li>
          <li><strong>Country:</strong> where SIUJI or the owners/founders of SIUJI are based, in this case is Indonesia</li>
          <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the SIUJI Service to manage the relationships with your consumers or service users.</li>
          <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit SIUJI and use the services.</li>
          <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
          <li><strong>Personnel:</strong> refers to those individuals who are employed by SIUJI or are under contract to perform a service on behalf of one of the parties.</li>
          <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
          <li><strong>Service:</strong> refers to the service provided by SIUJI as described in the relative terms (if available) and on this platform.</li>
          <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
          <li><strong>Website:</strong> SIUJI's site, which can be accessed via this URL</li>
          <li><strong>You:</strong> a person or entity that is registered with SIUJI to use the Services.</li>
        </ul>

        <h2>What Information Do We Collect?</h2>
        <h3>General Information</h3>
        <p>We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
        <ul>
          <li>Identity ID</li>
          <li>Name / Username</li>
          <li>Password</li>
          <li>Gender</li>
          <li>Birth Place</li>
          <li>Birth Date</li>
          <li>Phone Numbers</li>
          <li>Other Info (Marriage Status, Religious Belief, Last Education)</li>
          <li>Files and Docs</li>
        </ul>

        <h3>Mobile Device Information</h3>
        <p>We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
        <ul>
          <li><strong>Location (GPS):</strong> Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.</li>
          <li><strong>Camera (Pictures):</strong> Granting camera permission allows the user to upload any picture straight from the app, you can safely deny camera permissions for this app.</li>
          <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this app.</li>
        </ul>

        <h2>How Do We Use The Information We Collect?</h2>
        <p>Any of the information we collect from you may be used in one of the following ways:</p>
        <ul>
          <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
          <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
          <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
          <li>To process transactions</li>
          <li>To administer a contest, promotion, survey or other site feature</li>
          <li>To send periodic emails</li>
        </ul>

        <h2>When does SIUJI use end user information from third parties?</h2>
        <p>SIUJI will collect End User Data necessary to provide the SIUJI services to our customers.</p>
        <p>End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>

        <h2>When does SIUJI use customer information from third parties?</h2>
        <p>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a SIUJI customer, we receive information from a third party that provides automated fraud detection services to SIUJI. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>

        <h2>Do we share the information we collect with third parties?</h2>
        <p>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</p>

        <h2>Where and when is information collected from customers and end users?</h2>
        <p>SIUJI will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</p>

        <h2>How Do We Use Your Email Address?</h2>
        <p>By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party.</p>

        <h2>How Long Do We Keep Your Information?</h2>
        <p>We keep your information only so long as we need it to provide SIUJI to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.</p>

        <h2>How Do We Protect Your Information?</h2>
        <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.</p>

        <h2>Could my information be transferred to other countries?</h2>
        <p>SIUJI is incorporated in Indonesia. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data.</p>

        <h2>Is the information collected through the SIUJI Service secure?</h2>
        <p>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems.</p>

        <h2>Can I update or correct my information?</h2>
        <p>The rights you have to request updates or corrections to the information SIUJI collects depend on your relationship with SIUJI. Personnel may update or correct their information as detailed in our internal company employment policies.</p>

        <h2>Sale of Business</h2>
        <p>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of SIUJI or any of its Corporate Affiliates, or that portion of SIUJI or any of its Corporate Affiliates to which the Service relates.</p>

        <h2>Governing Law</h2>
        <p>This Privacy Policy is governed by the laws of Indonesia without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy.</p>

        <h2>Your Consent</h2>
        <p>We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our app, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</p>

        <h2>Links to Other Websites</h2>
        <p>This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by SIUJI. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.</p>

        <h2>Cookies</h2>
        <p>SIUJI uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use.</p>

        <h2>Kids' Privacy</h2>
        <p>We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

        <h2>Changes To Our Privacy Policy</h2>
        <p>We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy.</p>

        <h2>Third-Party Services</h2>
        <p>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").</p>

        <h2>Tracking Technologies</h2>
        <li>Local Storage</li>
        <p>Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.</p>

        <h2>Contact Us</h2>
        <p>Don't hesitate to contact us if you have any questions.</p>
        <p>Email: <a href="mailto:info@someah.id">info@someah.id</a></p>
      </div>
      
      <!-- Footer -->
      <div class="privacy-footer">
        <div class="footer-content">
          <img :src="logo" alt="SIUJI Logo" class="footer-logo" />
          <div class="footer-text">
            <p class="copyright">2025 © SIUJI.</p>
            <p class="developer">Develop by PT Someah Kreatif Nusantara</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { useRouter } from 'vue-router'
import logo from '@/assets/logo.svg'

const router = useRouter()

const goBack = () => {
  // Cek apakah ada history, jika tidak kembali ke home
  if (window.history.length > 1) {
    router.back()
  } else {
    router.push('/')
  }
}
</script>

<style scoped>
.privacy-policy-section {
  background: #f8fafc;
  min-height: 100vh;
  padding: 40px 0 60px 0;
  font-family: 'Inter', Arial, sans-serif;
}
.container {
  max-width: 1450px;
  margin: 0 auto;
  background: #fff;
  border-radius: 16px;
  box-shadow: 0 4px 24px rgba(0,0,0,0.07);
  padding: 32px 20px 40px 20px;
}

.logo-header {
  text-align: center;
  margin-bottom: 20px;
}

.logo {
  height: 60px;
  width: auto;
}

.back-button {
  background: #19c9b3;
  color: white;
  border: none;
  border-radius: 8px;
  padding: 10px 20px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-bottom: 20px;
  transition: all 0.3s ease;
  font-family: 'Inter', Arial, sans-serif;
  display: flex;
  align-items: center;
  gap: 8px;
}

.back-text {
  margin-left: 4px;
}

.back-button:hover {
  background: #16a085;
  transform: translateX(-2px);
}

h1 {
  font-size: 2.2rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
  color: #222;
  text-align: center;
}
.update-date {
  color: #888;
  font-size: 0.95rem;
  margin-bottom: 2rem;
  text-align: center;
}
.policy-content h2 {
  font-size: 2rem;
  font-weight: 600;
  margin-top: 2rem;
  margin-bottom: 0.5rem;
  color: #19c9b3;
}
.policy-content h3 {
    font-size: 1.5rem;
}
.policy-content p, .policy-content ul {
  font-size: 1rem;
  color: #333;
  margin-bottom: 1rem;
  line-height: 1.7;
}
.policy-content ul {
  padding-left: 1.2rem;
}
.policy-content li {
  margin-bottom: 0.5rem;
}
a {
  color: #19c9b3;
  text-decoration: underline;
}

.privacy-footer {
  margin-top: 3rem;
  padding-top: 2rem;
  border-top: 1px solid #e2e8f0;
}

.footer-content {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1rem;
  flex-wrap: wrap;
}

.footer-logo {
  height: 40px;
  width: auto;
}

.footer-text {
  text-align: center;
}

.footer-text .copyright {
  font-size: 0.9rem;
  font-weight: 600;
  color: #333;
  margin: 0 0 0.2rem 0;
}

.footer-text .developer {
  font-size: 0.8rem;
  color: #666;
  margin: 0;
}

@media (max-width: 600px) {
  .container {
    padding: 18px 6px 28px 6px;
    border-radius: 10px;
  }
  
  .logo {
    height: 45px;
  }
  
  .back-button {
    padding: 8px 16px;
    font-size: 0.9rem;
    margin-bottom: 15px;
  }
  
  h1 {
    font-size: 1.3rem;
  }
  .policy-content h2 {
    font-size: 1.05rem;
  }
  .policy-content p, .policy-content ul {
    font-size: 0.97rem;
  }
  
  .footer-content {
    flex-direction: column;
    gap: 0.5rem;
  }
  
  .footer-logo {
    height: 35px;
  }
}
</style>
