version: '3.8'

services:
  # Frontend Development
  frontend-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: siuji-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_CMS_URL=${VITE_CMS_URL}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - siuji-network

networks:
  siuji-network:
    driver: bridge